AllCops:
  Exclude:
    - 'bin/**/*'
    - 'assets/**/*'
  DisplayCopNames: true

Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
